<WindowManager>:
    MainScreen:
        name: "mainscreen"
    NetflixNewDataScreen:
        name: "netflixnewdatascreen"
    NetflixLoadingScreen:
        name: "netflixloadingscreen"
    NetflixUserScreen:
        name: "netflixuserscreen"
    SpotifyNewDataScreen:
        name: "spotifynewdatascreen"
    SpotifyLoginScreen:
        name: "spotifyloginscreen"
    SpotifyUserScreen:
        name: "spotifyuserscreen"
